#!/usr/bin/env bash

prof=$(grep -e "\[Profile0\]" -A 3 ~/.mozilla/firefox/profiles.ini | tail -n 1 | sed -e 's/Path=//g')
userjs=~/.mozilla/firefox/${prof}/user.js
colordiff -u user.js ${userjs}
cp user.js ${userjs} -v
